<?php

namespace Database\Factories;

use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Product>
 */
class ProductFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {   $productMap = [
                        'Smartphone' => 'A handheld mobile device that combines cellular communication, computing, and multimedia features, typically with a touchscreen interface, internet connectivity, and support for various apps.',
                        'Laptop' => 'A portable personal computer with a clamshell design, integrating a keyboard, touchpad, screen, and battery, suitable for mobile productivity, entertainment, and communication.',
                        'Wireless earbuds' => 'Small, battery-powered headphones that connect to devices via Bluetooth, offering untethered audio listening, often with a charging case for extended use.',
                        'Smartwatch' => 'A wrist-worn wearable device that provides notifications, fitness tracking, health monitoring, and app connectivity, often syncing with a smartphone.',
                        '4K Television' => 'A high-definition TV with a resolution of approximately 3840 x 2160 pixels, offering four times the detail of 1080p for sharper, more immersive viewing.',
                        'Tablet' => 'A flat, touchscreen mobile device larger than a smartphone but smaller than a laptop, used for browsing, media consumption, light productivity, and gaming.',
                        'Bluetooth speaker' => 'A wireless speaker that streams audio from devices like phones or laptops via Bluetooth, available in various sizes for portable or home use.',
                        'Gaming console' => 'A dedicated electronic device designed primarily for playing video games, often connected to a TV or monitor, with its own controllers and game library.',
                        'DSLR camera' => 'A digital camera using a mirror mechanism to reflect light from the lens to an optical viewfinder, offering interchangeable lenses and manual controls for high-quality photography.',
                        'Drone' => 'An unmanned aerial vehicle (UAV) controlled remotely, often equipped with a camera for aerial photography, videography, or recreational flying.',
                        'External hard drive' => 'A portable or desktop storage device that connects via USB, Thunderbolt, or other interfaces, providing additional backup or file storage for computers.',
                        'USB flash drive' => 'A small, plug-and-play data storage device with a USB interface, used for transferring or backing up files between computers and other devices.',
                        'Wi-Fi router' => 'A networking device that forwards data packets between computer networks, typically enabling multiple devices to share an internet connection wirelessly.',
                        'Power bank' => 'A portable rechargeable battery pack with USB ports, used to charge mobile devices like smartphones and tablets when no wall outlet is available.',
                        'LED monitor' => 'A flat-panel display using light-emitting diodes for backlighting, offering energy efficiency, thin profile, and good color accuracy for computers or TVs.',
                        'Graphics card' => 'A hardware component that renders images, video, and 3D graphics for display, essential for gaming, video editing, and other GPU-intensive tasks.',
                        'Mechanical keyboard' => 'A keyboard using individual mechanical switches under each key for tactile and audible feedback, preferred by gamers and typists for durability and feel.',
                        'Wireless mouse' => 'A pointing device that connects to a computer via radio frequency (usually Bluetooth or a USB dongle), eliminating the need for a cord.',
                        'Webcam' => 'A video camera that streams or captures video and sound for use with computers, typically for video conferencing, streaming, or online recording.',
                        'Noise-canceling headphones' => 'Headphones that use active noise control to reduce unwanted ambient sounds, providing a quieter listening experience, often with Bluetooth.',
                        'Streaming stick' => 'A small, HDMI-based media player that plugs directly into a TV’s HDMI port, providing access to streaming services like Netflix, Hulu, and YouTube.',
                        'Smart home hub' => 'A central device that connects and controls various smart home products (lights, locks, thermostats) using protocols like Zigbee, Z-Wave, or Wi-Fi.',
                        'Robot vacuum cleaner' => 'An autonomous robotic device that navigates floors to vacuum dust and debris, using sensors and sometimes mapping technology to avoid obstacles.',
                        'Electric toothbrush' => 'A battery-powered toothbrush with a vibrating or rotating bristle head to improve plaque removal and gum health compared to manual brushing.',
                        'Hair clipper' => 'An electric grooming device with sharp, adjustable blades used to cut or trim hair, commonly used for barbering or home haircuts.',
                        'Air purifier' => 'An appliance that removes airborne contaminants such as dust, pollen, pet dander, and smoke using filters (e.g., HEPA) or other technologies to improve indoor air quality.',
                        'Portable projector' => 'A compact, lightweight projector designed for easy transport, allowing users to display images and videos on any flat surface from various sources.',
                        'E-reader' => 'A handheld device designed primarily for reading digital e-books, typically using an electronic paper display for reduced eye strain and long battery life.',
                        'Dash cam' => 'A compact video camera mounted on a vehicle’s dashboard or windshield, continuously recording the road ahead to provide evidence in case of accidents or incidents.',
                        'Car jump starter' => 'A portable battery pack with heavy-duty cables and clamps, designed to jump-start a vehicle with a dead battery without needing another car.',
                        'Fitness tracker' => 'A wearable device that monitors physical activity, steps, heart rate, sleep patterns, and often syncs with a smartphone app to track fitness goals.',
                        'VR headset' => 'A head-mounted device that provides immersive virtual reality experiences by displaying stereoscopic 3D images and tracking head movements.',
                        'Computer cooling fan' => 'An active cooling component that draws or exhausts air across heat sinks inside a computer case to maintain optimal operating temperatures.',
                        'SSD' => 'A solid-state drive that stores data on flash memory chips, offering much faster read/write speeds, lower latency, and greater durability than traditional hard disk drives.',
                        'Universal power adapter' => 'A single AC power adapter with interchangeable plugs or voltage settings, allowing electronic devices to be used in different countries with various outlet types.',
                        'Cotton T-shirt' => 'A casual tops made primarily from soft, breathable cotton fabric, typically short-sleeved with a round neck, suitable for everyday wear.',
                        'Denim jeans' => 'Durable trousers made from denim fabric, characterized by rivets, pockets, and a sturdy construction, available in various fits and washes.',
                        'Hoodie' => 'A casual sweatshirt or jacket with a hood, often featuring a front pocket and drawstrings, made from cotton or fleece for warmth and comfort.',
                        'Winter puffer jacket' => 'An insulated jacket filled with down or synthetic fibers, quilted into sections (puffing), designed to trap body heat and protect against cold weather.',
                        'Leather belt' => 'A flexible strap made of leather, worn around the waist to hold up trousers or for fashion, typically with a buckle at one end.',
                        'Ankle socks' => 'Short socks that reach just above the ankle bone, worn with casual shoes or sneakers to provide comfort without being visible above low-cut footwear.',
                        'Running sneakers' => 'Athletic shoes designed specifically for running, featuring cushioning, arch support, and a lightweight, breathable upper to absorb impact and provide traction.',
                        'High-heeled pumps' => 'Women’s shoes with a raised heel, typically 2 inches or higher, a closed toe, and no laces, worn for formal occasions or to add height and elegance.',
                        'Baseball cap' => 'A soft cap with a rounded crown and a stiff brim projecting forward, often adjustable at the back, commonly used for sun protection or sports team branding.',
                        'Beanie hat' => 'A close-fitting, brimless knitted cap, usually made of wool or acrylic, worn for warmth in cold weather or as a casual fashion accessory.',
                        'Wool scarf' => 'A long, narrow piece of fabric woven from wool fibers, worn wrapped around the neck for warmth and style during cold seasons.',
                        'Leather gloves' => 'Hand coverings made from tanned animal hide, providing warmth, protection, and grip, often lined for comfort and used in cold weather or for dress.',
                        'Formal button-down shirt' => 'A collared shirt with a full front opening secured by buttons, typically made of woven cotton, worn with suits or trousers for business or formal occasions.',
                        'Blazer' => 'A type of jacket resembling a suit coat but more casual, often solid-colored with contrasting buttons, worn over a shirt for semi-formal or smart-casual attire.',
                        'Yoga pants' => 'Stretchy, form-fitting pants made from a blend of spandex and cotton or polyester, designed for flexibility and comfort during yoga, exercise, or casual wear.',
                        'Cargo shorts' => 'Short trousers with large, expandable pockets (cargo pockets) on the sides, typically made of heavy cotton, worn for outdoor activities or casual summer attire.',
                        'Swimsuit' => 'A garment designed for swimming and water activities, made of quick-drying, chlorine-resistant fabric, available as one-piece or two-piece for various coverage.',
                        'Sleepwear pajama set' => 'A coordinated two-piece set for sleeping, usually consisting of a loose button-up or pullover top and matching elastic-waist pants, made of soft cotton or flannel.',
                        'Boxer briefs' => 'Men’s underwear that combines the longer leg length of boxers with the snug fit of briefs, offering support and comfort with an elastic waistband.',
                        'Bra' => 'A form-fitting undergarment designed to support and cover the breasts, made of fabric with straps, cups, and often underwire or padding.',
                        'Kid’s school uniform shirt' => 'A standard, durable collared shirt (often polo or button-down) in specific school colors, designed for daily wear by children in an educational setting.',
                        'Down vest' => 'A sleeveless outer garment insulated with down feathers, worn over a shirt or sweater for core warmth without restricting arm movement.',
                        'Raincoat' => 'A waterproof or water-resistant coat, often made of treated nylon, polyester, or rubberized fabric, designed to protect the wearer from rain.',
                        'Denim jacket' => 'A jacket made from denim fabric, typically with button-front closure, chest pockets, and a relaxed fit, originating as workwear but now a fashion staple.',
                        'Sweater' => 'A knitted garment worn on the upper body, typically made of wool, cotton, or synthetic fibers, designed to provide warmth and available in various necklines and styles.',
                        'Loafers' => 'Slip-on dress-casual shoes with a low heel and a moccasin-like construction, often featuring a decorative strap or penny slot, suitable for office or smart casual.',
                        'Sandals' => 'Open-toed footwear consisting of a sole held to the foot by straps (often leather or synthetic), worn in warm weather or casual settings.',
                        'Winter boots' => 'Insulated, waterproof boots with deep treads, designed to keep feet warm and dry in snow, slush, and freezing temperatures.',
                        'Flip-flops' => 'Simple, flat, rubber-soled sandals with a Y-shaped strap that passes between the first and second toes, used for beaches, pools, or casual summer wear.',
                        'Tie' => 'A long, narrow strip of fabric worn around the neck, under a shirt collar, and knotted at the front, traditionally part of formal or business attire.',
                        'Suspenders' => 'Straps worn over the shoulders, attached to trousers with clips or buttons to hold them up, serving as an alternative to a belt.',
                        'Sports jersey' => 'A loose-fitting, often sleeveless or short-sleeved shirt displaying a team’s name, logo, and player number, worn by athletes or fans for sports events.',
                        'Tank top' => 'A sleeveless, collarless shirt with wide armholes and a low neckline, made of cotton or stretch fabric, worn for exercise or as casual summer wear.',
                        'Fleece jacket' => 'A soft, lightweight jacket made from synthetic polyester fleece fabric, providing warmth without bulk, often used for outdoor activities or layering.',
                        'Overalls' => 'One-piece work or casual garments combining trousers with a front bib and shoulder straps, usually made of denim or canvas, with several pockets.',
                        'Engine oil' => 'A lubricant composed of base oils and additives, used to reduce friction, cool, and clean internal combustion engines in cars and other vehicles.',
                        'Car battery' => 'A rechargeable lead-acid or AGM battery that provides electrical current to start the engine and power vehicle electronics when the alternator is not running.',
                        'Brake pads' => 'Friction material bonded to a metal backing plate, pressed against the brake rotor to slow or stop a vehicle as part of the disc brake system.',
                        'Windshield wiper blades' => 'Rubber blades attached to metal arms that sweep across the windshield, removing rain, snow, or debris to maintain clear visibility for the driver.',
                        'Tire' => 'A durable rubber ring, typically filled with air, mounted around a wheel to provide traction, cushioning, and support for a vehicle on roads.',
                        'Car cover' => 'A fitted protective fabric cover (weatherproof or breathable) placed over a parked car to shield it from dust, sun, rain, bird droppings, and minor scratches.',
                        'Floor mats' => 'Removable carpet or rubber mats placed on a vehicle’s floor, designed to trap dirt, mud, and moisture, protecting the original carpeting.',
                        'Car phone holder' => 'A mount that attaches to a car’s dashboard, windshield, or air vent, holding a smartphone securely for hands-free navigation and calls.',
                        'LED headlight bulbs' => 'High-intensity, energy-efficient light-emitting diode bulbs that replace halogen or HID bulbs in vehicle headlights, offering brighter and longer-lasting illumination.',
                        'Spark plugs' => 'Electrical devices that screw into an engine cylinder, delivering a spark to ignite the air-fuel mixture, initiating combustion in gasoline engines.',
                        'Oil filter' => 'A canister-type filter that removes contaminants (dirt, metal particles) from engine oil as it circulates, protecting the engine from wear.',
                        'Air filter' => 'A paper, foam, or cotton gauze filter that cleans the air entering a vehicle’s engine, preventing dust and debris from causing internal damage.',
                        'Cabin air filter' => 'A pleated filter, usually in the HVAC system, that cleans the air entering the car’s interior by trapping pollen, dust, and other airborne particles.',
                        'Car wax' => 'A natural or synthetic product (paste, liquid, or spray) applied to a car’s paint to add shine, protect from UV rays, and repel water.',
                        'Tire pressure gauge' => 'A handheld tool (digital or analog) used to measure the air pressure inside a vehicle tire, helping to maintain proper inflation for safety and efficiency.',
                        'Jumper cables' => 'Heavy-gauge, insulated copper cables with alligator clips on each end, used to transfer current from a live battery to a dead one to jump-start a vehicle.',
                        'Emergency roadside kit' => 'A pre-assembled collection of safety items (reflectors, first aid, jumper cables, flashlight, blanket) kept in a vehicle for unexpected breakdowns or accidents.',
                        'Seat covers' => 'Protective or decorative fabric covers that fit over a vehicle’s original seats, guarding against spills, stains, wear, and UV damage.',
                        'Steering wheel cover' => 'A removable sleeve (leather, rubber, or fabric) that wraps around the steering wheel rim, providing better grip, comfort, or protection from heat/cold.',
                        'Car vacuum cleaner' => 'A compact, often 12V-powered vacuum designed for cleaning dust, crumbs, and debris from car interiors, with attachments for crevices and upholstery.',
                        'FM Bluetooth transmitter' => 'A device that plugs into a car’s 12V outlet, receives Bluetooth audio from a phone, and transmits it over an FM frequency to the car’s radio.',
                        'Car interior cleaning wipes' => 'Pre-moistened disposable wipes formulated to clean and sometimes condition dashboard, vinyl, leather, and plastic surfaces without leaving residue.',
                        'License plate frame' => 'A metal or plastic border that attaches around the perimeter of a vehicle’s license plate, used for decoration or to display messages/branding.',
                        'Trunk organizer' => 'A collapsible or rigid storage unit with compartments, placed in a car trunk to keep groceries, tools, emergency items, and cargo neat and secure.',
                        'Hubcaps' => 'Decorative plastic or metal covers that snap onto a steel wheel to improve aesthetics, hiding the lug nuts and the wheel rim.',
                        'Basmati rice' => 'A long-grain, aromatic rice variety grown in India and Pakistan, known for its light, fluffy texture and distinct nutty fragrance when cooked.',
                        'Whole wheat bread' => 'A bread made from flour that contains the entire wheat kernel (bran, germ, endosperm), offering more fiber and nutrients than white bread.',
                        'Extra virgin olive oil' => 'The highest-grade olive oil, cold-pressed from fresh olives without chemicals or high heat, characterized by low acidity and rich, fruity flavor.',
                        'Pasta' => 'A staple Italian food made from durum wheat semolina and water, shaped into various forms (spaghetti, penne, macaroni) and boiled for meals.',
                        'Tomato ketchup' => 'A sweet and tangy condiment made from tomatoes, sugar, vinegar, and spices, used as a dipping sauce or topping for burgers, fries, and hot dogs.',
                        'Mayonnaise' => 'A thick, creamy emulsion of oil, egg yolk, vinegar or lemon juice, and seasonings, used as a spread, dressing, or base for other sauces.',
                        'Soy sauce' => 'A dark, salty fermented liquid condiment made from soybeans, wheat, salt, and a mold (koji), essential in many Asian cuisines.',
                        'Honey' => 'A sweet, viscous food substance produced by bees from flower nectar, used as a natural sweetener, spread, or remedy for sore throats.',
                        'Peanut butter' => 'A spread made from ground, dry-roasted peanuts, often with added salt, sweetener, and oil, smooth or chunky in texture.',
                        'Instant coffee' => 'A coffee powder or granules that dissolve in hot water to make a quick cup of coffee, made by dehydrating brewed coffee concentrate.',
                        'Black tea bags' => 'Infuser pouches containing dried leaves of the Camellia sinensis plant that have been fully oxidized (black tea), ready for steeping in hot water.',
                        'Whole milk' => 'Cow’s milk that has not had any fat removed, typically containing about 3.25% milkfat, with a creamy texture and rich flavor.',
                        'Cheddar cheese' => 'A firm, smooth, pale yellow-to-orange cheese originally from England, ranging from mild to extra sharp, commonly used for sandwiches, melting, or eating raw.',
                        'Butter' => 'A dairy product made by churning fresh or fermented cream or milk, separating butterfat from buttermilk, used as a spread, cooking fat, or baking ingredient.',
                        'Chicken eggs' => 'A common food product from hens, consisting of a shell, egg white (albumen), and yolk, rich in protein and used in baking, frying, boiling, or scrambling.',
                        'Frozen mixed vegetables' => 'A bagged blend of frozen vegetables (typically peas, corn, carrots, green beans), blanched and flash-frozen to preserve nutrients and texture for convenient cooking.',
                        'Frozen pizza' => 'A pre-assembled, uncooked or par-baked pizza that is frozen for storage, requiring only oven heating before serving.',
                        'Vanilla ice cream' => 'A frozen dessert made from cream, milk, sugar, and vanilla extract or vanilla bean specks, churned to incorporate air for a smooth, scoopable texture.',
                        'Potato chips' => 'Thin slices of potato that have been deep-fried or baked until crispy, salted and often flavored, sold as a snack food.',
                        'Tortilla chips' => 'Triangular or round chips made from fried corn tortillas, salted, and commonly served with salsa, guacamole, or cheese dip.',
                        'Salsa' => 'A Mexican sauce or dip typically made from tomatoes, onions, chili peppers, cilantro, and lime juice, ranging from mild to hot, served with tortilla chips.',
                        'Chocolate bar' => 'A solid confectionery bar made from cocoa solids, cocoa butter, sugar, and often milk powder, sometimes with inclusions like nuts or caramel.',
                        'Granola bars' => 'A baked snack bar made from rolled oats, honey, nuts, dried fruit, and often chocolate chips, held together by a sweet binder.',
                        'Instant oatmeal' => 'Pre-cooked, dried, and flattened rolled oats that rehydrate quickly with hot water or milk, often sold in flavored packets for a quick breakfast.',
                        'Canned tuna' => 'Cooked tuna fish (usually skipjack or albacore) packed in water, brine, or oil inside a sealed metal can, ready to eat or use in salads and sandwiches.',
                        'Canned black beans' => 'Pre-cooked black beans preserved in water and salt inside a sealed can, requiring only draining and rinsing before use.',
                        'Chicken broth' => 'A savory liquid made by simmering chicken meat and bones with vegetables and herbs, strained and used as a base for soups, stews, and sauces.',
                        'All-purpose flour' => 'A medium-protein wheat flour that can be used for a wide range of baking and cooking, from bread to pastries, usually enriched and bleached or unbleached.',
                        'White sugar' => 'Refined sucrose from sugar cane or sugar beets, granulated and white, used as a common sweetener in baking, beverages, and cooking.',
                        'Salt' => 'Sodium chloride (NaCl), a crystalline mineral essential for human health and widely used as a seasoning and preservative in food.',
                        'Black pepper' => 'A pungent, spicy seasoning made from dried, unripe berries of the Piper nigrum vine, ground or used whole as a table and cooking spice.',
                        'Pasta sauce' => 'A savory, typically tomato-based sauce (marinara, arrabbiata) with herbs, garlic, and onions, cooked and jarred for pouring over pasta.',
                        'Orange juice' => 'A fruit juice extracted from oranges, often pasteurized and sold fresh or from concentrate, rich in vitamin C, consumed as a breakfast beverage.',
                        'Soft drink' => 'A carbonated, sweetened non-alcoholic beverage, typically flavored with cola, fruit, or ginger, containing caffeine or not.',
                        'Bottled water' => 'Drinking water packaged in plastic or glass bottles, either purified, spring, mineral, or distilled, for portable consumption.',
                        'Hammer' => 'A hand tool with a heavy metal head mounted on a handle, used for driving nails, breaking objects, or shaping metal.',
                        'Phillips screwdriver set' => 'A set of hand tools with a cruciform (cross-shaped) tip, designed to drive or remove Phillips-head screws in various sizes.',
                        'Cordless drill' => 'A battery-powered rotary tool with a chuck that accepts drill bits or screwdriver bits, used for drilling holes or driving fasteners without a cord.',
                        'Tape measure' => 'A flexible ruler made of metal or fiberglass that retracts into a housing, marked with length measurements, used for measuring distances and dimensions.',
                        'Utility knife' => 'A retractable or fixed-blade knife with replaceable snap-off blade segments, used for cutting cardboard, drywall, carpet, and other materials.',
                        'Level' => 'A tool containing one or more liquid-filled vials with an air bubble, used to determine if a surface is horizontally or vertically true.',
                        'Adjustable wrench' => 'A wrench with a movable jaw that can be adjusted to different sizes of nuts or bolt heads, allowing one tool to replace several fixed sizes.',
                        'Pliers' => 'A hand tool with opposing jaws, used for gripping, bending, cutting, or turning wires and small objects, with various tip shapes (needle-nose, slip-joint).',
                        'Hex key set' => 'A set of L-shaped hexagonal wrenches (Allen keys) made of hardened steel, used to drive socket-head screws and bolts in machinery and furniture assembly.',
                        'Hacksaw' => 'A fine-toothed, tensioned saw blade held in a C-shaped frame, used for cutting metal, plastic, or PVC pipe.',
                        'Circular saw' => 'A power saw with a toothed or abrasive disc (blade) that rotates rapidly, used for making straight cuts in wood, metal, or masonry.',
                        'Nails' => 'Slender metal rods with a pointed tip and a flattened head, driven into wood or other materials with a hammer to fasten objects together.',
                        'Wood screws' => 'Threaded fasteners with a tapered shank and a sharp point, designed to cut their own threads into wood, available with various head types (flat, round, pan).',
                        'Drywall anchors' => 'Plastic or metal inserts that expand behind drywall when a screw is driven into them, providing secure mounting for objects where no stud is present.',
                        'Sandpaper' => 'A coated abrasive material consisting of abrasive grains (aluminum oxide, silicon carbide) glued to a paper or cloth backing, used for smoothing or polishing surfaces.',
                        'Paint roller kit' => 'A set including a roller frame, a replaceable roller cover (nap), and a paint tray, used to apply paint efficiently to large, flat surfaces.',
                        'Latex paint' => 'A water-based paint with acrylic or vinyl acrylic resins, offering low odor, easy cleanup with soap and water, and durability for interior or exterior walls.',
                        'Paintbrush set' => 'A collection of brushes with natural or synthetic bristles in different widths and shapes (flat, angled), used for cutting in edges and painting trim or small areas.',
                        'Masking tape' => 'A lightly adhesive, pressure-sensitive tape made of thin paper, easy to tear and remove without leaving residue, used to protect surfaces during painting.',
                        'Duct tape' => 'A strong, cloth-backed, waterproof pressure-sensitive tape with a polyethylene coating, highly adhesive, used for repairs, sealing, and temporary fixes.',
                        'Caulk gun' => 'A handheld tool designed to apply caulk or sealant from a cartridge, using a trigger-operated plunger to push the material out through a nozzle.',
                        'Silicone caulk' => 'A flexible, waterproof sealant made from silicone rubber, used to seal gaps around windows, tubs, sinks, and countertops, resisting mold and weathering.',
                        'Wire nuts' => 'Conical, threaded plastic connectors with a metal spring inside, used to twist and cap the ends of electrical wires together for a safe, insulated splice.',
                        'Electrical tape' => 'A pressure-sensitive vinyl tape with insulating and flame-retardant properties, used to wrap and insulate electrical wires and connections.',
                        'Wall outlet' => 'A recessed electrical socket mounted in a wall, typically providing 15 or 20 amps at 120 volts, with slots for plugging in appliances and devices.',
                        'Light switch' => 'An electrical wall-mounted device that manually makes or breaks the circuit to control lighting or other electrical loads, typically a single-pole or three-way.',
                        'PVC pipe' => 'A rigid, lightweight white or gray plastic pipe made from polyvinyl chloride, used for cold water supply, drainage, and electrical conduit.',
                        'PVC cement' => 'A solvent-based adhesive that chemically fuses PVC pipe and fittings together by softening the plastic, creating a permanent, watertight bond.',
                        'Copper pipe' => 'A durable metal pipe made of copper, used for hot and cold water supply lines in residential plumbing, available in rigid lengths or flexible rolls.',
                        'Pipe wrench' => 'An adjustable, self-locking wrench with serrated jaws, designed to grip and turn threaded pipes and fittings, applying high torque.',
                        'Plunger' => 'A plumbing tool with a rubber suction cup attached to a wooden or plastic handle, used to clear clogs in toilets and drains by creating pressure and vacuum.',
                        'Work gloves' => 'Hand protection made of leather, synthetic leather, or coated fabric, providing grip, abrasion resistance, and protection from dirt, splinters, and minor cuts.',
                        'Safety goggles' => 'Impact-resistant eyewear with a tight seal around the eyes, protecting against flying debris, dust, or chemical splashes in workshop or construction environments.',
                        'Dust mask' => 'A disposable mask (often N95-rated) worn over the nose and mouth, filtering at least 95% of airborne particles, used during sanding, sweeping, or cutting.',
                        'Hinges' => 'A mechanical bearing that connects two solid objects (door to frame) while allowing a limited angle of rotation, available in butt, continuous, or pivot styles.',
                        'Queen bed frame' => 'A metal or wooden structural base designed to support a queen-size mattress (60" x 80"), typically including side rails, headboard brackets, and center support legs.',
                        'Mattress' => 'A large, thick pad of fabric-covered foam, innersprings, or hybrid materials, used as a sleeping surface on a bed frame, sized for a bed (twin, queen, etc.).',
                        '3-seater sofa' => 'An upholstered seating unit with back and armrests, designed for three people, typically used in living rooms or lounges as primary seating.',
                        'Recliner chair' => 'An armchair with a mechanism that allows the occupant to lower the back and raise the footrest by leaning back or operating a lever, for relaxation.',
                        'Coffee table' => 'A low rectangular table placed in front of a sofa, used for holding drinks, books, remotes, and decorative items in a living room.',
                        'End table' => 'A small, often square or round table placed beside a sofa or armchair, used for a lamp, drinks, or personal items.',
                        'Dining table' => 'A raised, flat-topped table designed for eating meals, typically surrounded by chairs, available in various shapes (rectangular, round) and seating capacities.',
                        'Dining chair' => 'A single-seat chair with a vertical back, intended for use at a dining table, typically without armrests for easy pushing under.',
                        'Bookshelf' => 'A vertical shelving unit with multiple horizontal shelves, designed to store books, decor, and other items, open or with glass doors.',
                        'Desk' => 'A furniture piece with a flat surface and sometimes drawers, used for reading, writing, computer work, or studying, in homes or offices.',
                        'Office chair' => 'An adjustable, wheeled swivel chair designed for use at a desk in an office, featuring lumbar support, padded seat, and armrests.',
                        'Dresser' => 'A piece of wooden furniture with several stacked drawers (usually 4-8) for storing clothing and personal items, often topped with a mirror.',
                        'Nightstand' => 'A small bedside table or cabinet, typically with one drawer or shelf, used to hold a lamp, alarm clock, books, or personal items within reach of a bed.',
                        'Wardrobe' => 'A tall, freestanding cabinet with hanging space (a rod) and often shelves or drawers, used for storing clothing without a built-in closet.',
                        'TV stand' => 'A low, elongated piece of furniture designed to support a television, often with open shelves, drawers, or cabinets for media components and accessories.',
                        'Bench' => 'A long, backless (or sometimes backed) seating piece for multiple people, made of wood, metal, or upholstered, used in entryways, gardens, or dining tables.',
                        'Ottoman' => 'A padded, upholstered seat or footstool without back or arms, often used as a coffee table substitute or extra seating, sometimes with hidden storage.',
                        'Folding chair' => 'A lightweight, portable chair with a hinge mechanism that allows it to collapse flat for storage, commonly made of metal tubing and plastic or padded seat.',
                        'Patio lounge chair' => 'An outdoor chaise-style chair with an adjustable back, often made of weather-resistant wicker, aluminum, or teak with a removable cushion for sunbathing.',
                        'Bistro table' => 'A small, round, pedestal-style table approximately 24 inches high, designed for intimate seating of two, used on patios, balconies, or small kitchens.',
                        'Folding table' => 'A portable table with legs that hinge and lock into place or fold flat against the underside, used for events, camping, or extra dining space.',
                        'Bar stool' => 'A tall, often backless stool designed for use at a bar or high counter, typically with a footrest ring and seat heights of 24-30 inches.',
                        'Shoe rack' => 'A single-tier or multi-tier storage unit (wood, metal, or fabric) designed to hold shoes off the floor, often placed in closets or entryways.',
                        'Coat rack' => 'A freestanding pole or wall-mounted fixture with multiple protruding pegs or hooks, used to hang coats, hats, scarves, and bags.',
                        'Wall shelf' => 'A flat shelf fixed directly to a wall with brackets or concealed hardware, used for display or lightweight storage without taking floor space.',
                        'Corner shelf' => 'A triangular or quarter-circle shelf designed to fit into a corner, maximizing unused space in a room, often used for plants, books, or decorations.',
                        'Futon' => 'A versatile piece of furniture that converts from a sofa to a bed by folding or sliding, using a thin mattress over a collapsible frame.',
                        'Murphy bed kit' => 'Hardware and instructions for building a wall-mounted fold-up bed that hinges into a cabinet or pocket when not in use, saving floor space.',
                        'Crib' => 'A small, enclosed bed specifically designed for infants, with high, slatted sides to prevent falls, often convertible to a toddler bed.',
                        'Changing table' => 'A raised, flat surface with safety rails and storage shelves or drawers, designed for diapering a baby, often with a padded changing pad.',
                        'Hammock' => 'A suspended, swinging fabric or mesh bed made of cotton, polyester, or rope, hung between two points (trees, stands) for relaxation or sleeping outdoors.',
                        'Desk lamp' => 'A small, task-oriented lamp with a base and adjustable arm or shade, placed on a desk to provide focused, direct light for reading or working.',
                        'Floor lamp' => 'A tall, freestanding lamp with a weighted base, vertical pole, and a lampshade at the top, used for ambient or task lighting in a room.',
                        'Filing cabinet' => 'A lockable, vertical or lateral storage unit with drawers designed to hang letter- or legal-size file folders for organizing papers and documents.',
                        'Storage cube organizer' => 'A modular, cubby-style shelving unit (usually 3x3 or 2x4) made of particleboard or fabric, used with folding fabric bins for storing toys, clothes, or accessories.',
                    ];
        $productName = $this->faker->randomElement(array_keys($productMap));
        $description = $productMap[$productName];
        return [
                'name' => $productName,
                'description' => $description,
                'price' => $this->faker->randomFloat(2, 200, 20000),
                'stock_quantity' => $this->faker->numberBetween(20, 2000)
        ];
    }
}
